---
# Source: opentelemetry-collector/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    helm.sh/chart: opentelemetry-collector-0.27.0
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "0.58.0"
    app.kubernetes.io/managed-by: Helm
data:
  relay: |
    extensions:
      health_check: {}
      memory_ballast: {}
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_mib: 1638
        spike_limit_mib: 512
      transform:
        logs:
          queries:
            # The OpenTelemetry log SDK says the trace context should be encoded in trace_id and span_id,
            # but New Relic conventions expects the fields to be dot delimited trace.id and span.id. We
            # use the transform processor to replace trace_id => trace.id, span_id => span.id.
            # https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/README.md#trace-context-in-legacy-formats
            - replace_pattern(body, "\"trace_id\":", "\"trace.id\":")
            - replace_pattern(body, "\"span_id\":", "\"span.id\":")
    exporters:
      logging: {}
      otlp:
        endpoint: https://otlp.eu01.nr-data.net:4317
        headers:
          api-key: {{ .Values.newRelicLicenseKey }}
    service:
      extensions:
      - health_check
      - memory_ballast
      pipelines:
        traces:
          exporters:
          - logging
          - otlp
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          address: 0.0.0.0:8888
