apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.dockerhubName }}/{{ .Values.name }}"
          ports:
            - protocol: TCP
              containerPort: {{ .Values.port }}
            - protocol: TCP
              containerPort: {{ .Values.portPrometheus }}
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 1000Mi
